[ETFE-3097] - Add continue draft page for CoD
hmrc/emcs-tfe-change-destination-frontend pull request #26
Opened 2024-01-17 10:14 UTC by LewisMitchell

2024-01-17 16:13 UTC, james-work-account requested changes

2024-01-17 16:56 UTC, LewisMitchell commented on app/controllers/IndexController.scala
>      }
Done in [ef8bfe1](https://github.com/hmrc/emcs-tfe-change-destination-frontend/pull/26/commits/ef8bfe1ee41aef55fc1ee38c19f1ce19370979fc)

2024-01-17 16:56 UTC, LewisMitchell commented on app/controllers/IndexController.scala
> +    (authAction(ern, arc) andThen userAllowed andThen withMovement.upToDate(arc) andThen getData).async { implicit request =>
Done in [ef8bfe1](https://github.com/hmrc/emcs-tfe-change-destination-frontend/pull/26/commits/ef8bfe1ee41aef55fc1ee38c19f1ce19370979fc)

2024-01-17 16:56 UTC, LewisMitchell commented on app/controllers/IndexController.scala
> +    (authAction(ern, arc) andThen userAllowed andThen withMovement.upToDate(arc) andThen getData).async { implicit request =>
Done in [ef8bfe1](https://github.com/hmrc/emcs-tfe-change-destination-frontend/pull/26/commits/ef8bfe1ee41aef55fc1ee38c19f1ce19370979fc)

2024-01-18 09:12 UTC, james-work-account approved these changes

2024-01-18 09:32 UTC, merged