ETFE-4257 Adding GuarantorNotRequired (value of 0)
hmrc/emcs-tfe-change-destination-frontend pull request #56
Opened 2024-07-08 13:37 UTC by grahampaulcook

2024-07-08 16:23 UTC, james-work-account requested changes
GuarantorArrangerPage might need updating too to cater for `0`.

2024-07-09 07:14 UTC, grahampaulcook commented
> GuarantorArrangerPage might need updating too to cater for `0`.

Updated at https://github.com/hmrc/emcs-tfe-change-destination-frontend/pull/56/commits/e8da4e48802f399d56282bb97a613e7f543a906b

2024-07-09 08:48 UTC, grahampaulcook commented
> > GuarantorArrangerPage might need updating too to cater for `0`.
> 
> Updated at [e8da4e4](https://github.com/hmrc/emcs-tfe-change-destination-frontend/commit/e8da4e48802f399d56282bb97a613e7f543a906b)

Adjusted https://github.com/hmrc/emcs-tfe-change-destination-frontend/pull/56/commits/34b567e6f84dfdaca3de85ad953243281772a285

2024-07-09 08:55 UTC, james-work-account approved these changes

2024-07-09 09:01 UTC, merged